openapi: 3.0.0
info:
  title: "Orders"
  version: "1.0"
servers:
  - url: https://dpc-api-marketplace-dev.apigee.net/orders
paths:
  /orders:
    get:
      summary: Get all orders
      operationId: Get all orders
      description: Get all orders
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/orders"
              example:
                orders:
                  - orderId: 61knu8gol56
                    billingAddress: 999 Nobel Road
                    cartToken: cHlwV0YX
                    datePurchased: "2020-07-22T12:45:03Z"
                    currency: AUD
                    paymentDetails: jcb
                    shippingAddress: 874 Graceland Court
                    totalPrice: $110.57
                    userId: gfrayne9
                  - orderId: 9zyjdp268w
                    billingAddress: 39 Coleman Drive
                    cartToken: hoY6EK1c
                    datePurchased: "2020-07-22T12:45:03Z"
                    currency: CNY
                    paymentDetails: jcb
                    shippingAddress: 3560 Larry Park
                    totalPrice: $8.71
                    userId: mrawlence1
  /orders/{orderId}:
    get:
      summary: Get a specific order
      operationId: Get a specific order
      security:
        - ApiKeyAuth: []
      parameters:
        - name: orderId
          in: path
          description: order id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orders"
              example:
                orderId: 61knu8gol56
                billingAddress: 999 Nobel Road
                cartToken: cHlwV0YX
                datePurchased: "2020-07-22T12:45:03Z"
                currency: AUD
                paymentDetails: jcb
                shippingAddress: 874 Graceland Court
                totalPrice: $110.57
                userId: gfrayne9
    post:
      summary: Create a new order
      operationId: Create order
      description: Create a new order.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: orderId
          in: path
          description: order id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/orders"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orders"
              example:
                orderId: 61knu8gol56
                billingAddress: 999 Nobel Road
                cartToken: cHlwV0YX
                datePurchased: "2020-07-22T12:45:03Z"
                currency: AUD
                paymentDetails: jcb
                shippingAddress: 874 Graceland Court
                totalPrice: $110.57
                userId: gfrayne9
    put:
      summary: Update a specific order
      operationId: Update an order
      security:
        - ApiKeyAuth: []
      parameters:
        - name: orderId
          in: path
          description: order id
          required: true
          schema:
            type: string
            format: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/orders"
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: apikey
  schemas:
    orders:
      type: object
      properties:
        billingAddress:
          type: string
          description: Billing Address.
        cartToken:
          type: string
          description: Cart token with products purchased
        datePurchased:
          type: string
          description: Date when the customer purchased this cart.
        currency:
          type: string
          description: Status of the package
        paymentDetails:
          type: string
          description: Payment detaols
        shippingAddress:
          type: string
          description: Shipping address.
        totalPrice:
          type: string
          description: Total price of the order.
        userId:
          type: string
          description: User ID that purchased the order
      required:
        - cartToken
        - billingAddress
        - currency
        - paymentDetails
        - shippingAddress
        - totalPrice
        - userId
